version: '3'

services:

  server:
    container_name: deno-container
    image: denoland/deno
    volumes:
      - ./server:/src
    working_dir: /src
    command: deno run --allow-net server.ts
    ports:
      - 8000:8000

  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
