version: '3'

services:

  server:
    container_name: deno-container
    image: denoland/deno
    volumes:
      - ./server:/src
    working_dir: /src
    command: deno run --allow-net server.ts
    ports:
      - 8000:8000

  redis-writer:
    container_name: redis-writer
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-writer-data:/data
  
  redis-reader:
    container_name: redis-reader
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis-reader-data:/data
    command: redis-server --slaveof redis-writer 6379

volumes:
  redis-writer-data:
  redis-reader-data:
