server: 
	deno run --allow-net server.ts

server/dev:
	denon run --allow-net server.ts

container/build:
	docker build . -t deno-server

container/run:
	docker run --name deno-server -p 8000:8000 deno-server 

